### ISSUE TITLE
Panel resetting when changing browser tab

### ISSUE THREAD

**Issue by ORanuare** [pydantic/logfire#1325]
### Description

I have a query health check custom dashboard; it shows the N+1 queries used in spans.

When I click a trace_id, it opens a new browser tab with all the span information that I need. The problem is that the previous tab where I clicked the trace_id, it refreshes, and I lose the one I clicked.

I'll leave the JSON from that dashboard.

Update: By simply changing Chrome tabs without clicking anything, it also resets the table. Is this a bug, or did I do something wrong?

```
{
  "kind": "Dashboard",
  "metadata": {
    "name": "Query Health Check",
    "createdAt": "2025-08-16T19:50:34.320655Z",
    "updatedAt": "2025-08-16T22:26:14.659266Z",
    "version": 0,
    "project": "boostshop"
  },
  "spec": {
    "display": {
      "name": "N+1 Queries",
      "description": null
    },
    "panels": {
      "N+1Queries": {
        "kind": "Panel",
        "spec": {
          "display": {
            "name": "N+1 Queries"
          },
          "plugin": {
            "kind": "Table",
            "spec": {}
          },
          "queries": [
            {
              "kind": "NonTimeSeriesQuery",
              "spec": {
                "plugin": {
                  "kind": "LogfireNonTimeSeriesQuery",
                  "spec": {
                    "query": "SELECT\n    t1.trace_id,\n    t2.span_name AS parent_span_name,\n    SUBSTR(t1.\"_lf_attributes/db.statement\", 1, 50) AS query_template,\n    COUNT(*) AS executions\nFROM records t1\nINNER JOIN records t2 ON t1.parent_span_id = t2.span_id\nWHERE\n    t1.\"_lf_attributes/db.statement\" LIKE 'SELECT%'\nGROUP BY\n    t1.trace_id,\n    parent_span_name,\n    query_template\nHAVING\n    COUNT(*) > 1\nORDER BY\n    executions DESC"
                  }
                }
              }
            }
          ]
        }
      }
    },
    "layouts": [
      {
        "kind": "Grid",
        "spec": {
          "display": {
            "title": "Panel Group",
            "collapse": {
              "open": true
            }
          },
          "items": [
            {
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "content": {
                "$ref": "#/spec/panels/N+1Queries"
              }
            }
          ]
        }
      }
    ],
    "variables": [],
    "duration": "1h",
    "refreshInterval": "0s",
    "datasources": {}
  }
}
```

### Python, Logfire & OS Versions, related packages (not required)

```TOML

```

**Comment by ddanielcruzz** [comment]
Hi @ORanuare, it is in fact a bug. I already got a fix for it and should be deployed most likely tomorrow. Thanks for reporting it!

**Comment by ddanielcruzz** [comment]
@ORanuare the fix is deployed. Let us know if you encounter any other issues. Thanks!

**Comment by ORanuare** [comment]
Hello! The problem is still there. I'll attach a video so you can see what I mean.

https://github.com/user-attachments/assets/ce496a45-5294-46ad-a2de-ecf7e0b34720

**Comment by ddanielcruzz** [comment]
Hey @ORanuare , thank you for sharing the video, that really helps. I think what you are seeing is a different issue from the one originally reported, or at least different from the one I was able to reproduce.

In the original case the problem was that scrolling was reset. For example, if you were at position 50, then switched tabs and came back, the scroll would reset to position 1.

From the video you shared, it looks like the scrolling position is preserved, but the order of the results changes. This can happen because we refetch data for the panels that are currently visible, and without a stable ordering the API may return rows in a slightly different order each time. To make sure results stay consistent, could you try adding an explicit ordering like this?

```sql
ORDER BY executions DESC, trace_id ASC;
```

Let me know if that helps, or if you are still seeing unexpected behavior.

**Comment by ORanuare** [comment]
That fixed my issue, thank you so much!
